user:
  name: 50
project:
  max_image_files: 5
  item: 3
per_page:
  project: 20
  user: 16
format:
  image: ["jpg", "jpeg", "gif", "png"]
  image_size: 0.5
description: 82
limit_project: 6
employees: 10000
completed_project: 173
client: 106
cup_of_coffee: 297345
